//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Rationally.Visio {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Messages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Rationally.Visio.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only open this wizard while working on a rationally document..
        /// </summary>
        internal static string Warning_WizardOnlyOnRationallyTemplates_Description {
            get {
                return ResourceManager.GetString("Warning_WizardOnlyOnRationallyTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Not Available.
        /// </summary>
        internal static string Warning_WizardOnlyOnRationallyTemplates_Label {
            get {
                return ResourceManager.GetString("Warning_WizardOnlyOnRationallyTemplates_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create View.
        /// </summary>
        internal static string Wizard_CreateButton_CreateView {
            get {
                return ResourceManager.GetString("Wizard_CreateButton_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update View.
        /// </summary>
        internal static string Wizard_CreateButton_UpdateView {
            get {
                return ResourceManager.GetString("Wizard_CreateButton_UpdateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationally - Configure Decision View.
        /// </summary>
        internal static string Wizard_Label_CreateView {
            get {
                return ResourceManager.GetString("Wizard_Label_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationally - Update Decision View.
        /// </summary>
        internal static string Wizard_Label_UpdateView {
            get {
                return ResourceManager.GetString("Wizard_Label_UpdateView", resourceCulture);
            }
        }
    }
}
