//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rationally.Visio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rationally.Visio.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only open this wizard while working on a rationally document..
        /// </summary>
        internal static string Warning_WizardOnlyOnRationallyTemplates_Description {
            get {
                return ResourceManager.GetString("Warning_WizardOnlyOnRationallyTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Not Available.
        /// </summary>
        internal static string Warning_WizardOnlyOnRationallyTemplates_Label {
            get {
                return ResourceManager.GetString("Warning_WizardOnlyOnRationallyTemplates_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create View.
        /// </summary>
        internal static string Wizard_CreateButton_CreateView {
            get {
                return ResourceManager.GetString("Wizard_CreateButton_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update View.
        /// </summary>
        internal static string Wizard_CreateButton_UpdateView {
            get {
                return ResourceManager.GetString("Wizard_CreateButton_UpdateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationally - Configure Decision View.
        /// </summary>
        internal static string Wizard_Label_CreateView {
            get {
                return ResourceManager.GetString("Wizard_Label_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationally - Update Decision View.
        /// </summary>
        internal static string Wizard_Label_UpdateView {
            get {
                return ResourceManager.GetString("Wizard_Label_UpdateView", resourceCulture);
            }
        }
    }
}
