//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rationally.Visio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rationally.Visio.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string AlternativeState_Accepted {
            get {
                return ResourceManager.GetString("AlternativeState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenged.
        /// </summary>
        internal static string AlternativeState_Challenged {
            get {
                return ResourceManager.GetString("AlternativeState_Challenged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarded.
        /// </summary>
        internal static string AlternativeState_Discarded {
            get {
                return ResourceManager.GetString("AlternativeState_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed.
        /// </summary>
        internal static string AlternativeState_Proposed {
            get {
                return ResourceManager.GetString("AlternativeState_Proposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string AlternativeState_Rejected {
            get {
                return ResourceManager.GetString("AlternativeState_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the header or totals row is not allowed..
        /// </summary>
        internal static string CannotDeleteForceHeaderFooter {
            get {
                return ResourceManager.GetString("CannotDeleteForceHeaderFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add alternative.
        /// </summary>
        internal static string Menu_AddAlternative {
            get {
                return ResourceManager.GetString("Menu_AddAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this alternative.
        /// </summary>
        internal static string Menu_DeleteAlternative {
            get {
                return ResourceManager.GetString("Menu_DeleteAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set State.
        /// </summary>
        internal static string Menu_SetState {
            get {
                return ResourceManager.GetString("Menu_SetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the alternatives container is allowed..
        /// </summary>
        internal static string OneAlternativesContainerAllowed {
            get {
                return ResourceManager.GetString("OneAlternativesContainerAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the forces container is allowed..
        /// </summary>
        internal static string OneForcesContainerAllowed {
            get {
                return ResourceManager.GetString("OneForcesContainerAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the information container is allowed..
        /// </summary>
        internal static string OneInformationContainerAllowed {
            get {
                return ResourceManager.GetString("OneInformationContainerAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the planning container is allowed..
        /// </summary>
        internal static string OnePlanningContainerAllowed {
            get {
                return ResourceManager.GetString("OnePlanningContainerAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the related documents container is allowed..
        /// </summary>
        internal static string OneRelatedDocumentsContainerAllowed {
            get {
                return ResourceManager.GetString("OneRelatedDocumentsContainerAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the stakeholders container is allowed..
        /// </summary>
        internal static string OneStakeholdersContainerAllowed {
            get {
                return ResourceManager.GetString("OneStakeholdersContainerAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the title box is allowed..
        /// </summary>
        internal static string OneTitleAllowed {
            get {
                return ResourceManager.GetString("OneTitleAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add alternative.
        /// </summary>
        internal static string Scope_AddAlternative {
            get {
                return ResourceManager.GetString("Scope_AddAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add related file.
        /// </summary>
        internal static string Scope_AddFile {
            get {
                return ResourceManager.GetString("Scope_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add force.
        /// </summary>
        internal static string Scope_AddForce {
            get {
                return ResourceManager.GetString("Scope_AddForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Planning item.
        /// </summary>
        internal static string Scope_AddPlanningItem {
            get {
                return ResourceManager.GetString("Scope_AddPlanningItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add stakeholder.
        /// </summary>
        internal static string Scope_AddStakeholder {
            get {
                return ResourceManager.GetString("Scope_AddStakeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add related url.
        /// </summary>
        internal static string Scope_AddUrl {
            get {
                return ResourceManager.GetString("Scope_AddUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click checkbox.
        /// </summary>
        internal static string Scope_CheckboxClick {
            get {
                return ResourceManager.GetString("Scope_CheckboxClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only open this wizard while working on a rationally document..
        /// </summary>
        internal static string Warning_WizardOnlyOnRationallyTemplates_Description {
            get {
                return ResourceManager.GetString("Warning_WizardOnlyOnRationallyTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Not Available.
        /// </summary>
        internal static string Warning_WizardOnlyOnRationallyTemplates_Label {
            get {
                return ResourceManager.GetString("Warning_WizardOnlyOnRationallyTemplates_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create View.
        /// </summary>
        internal static string Wizard_CreateButton_CreateView {
            get {
                return ResourceManager.GetString("Wizard_CreateButton_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update View.
        /// </summary>
        internal static string Wizard_CreateButton_UpdateView {
            get {
                return ResourceManager.GetString("Wizard_CreateButton_UpdateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationally - Configure Decision View.
        /// </summary>
        internal static string Wizard_Label_CreateView {
            get {
                return ResourceManager.GetString("Wizard_Label_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rationally - Update Decision View.
        /// </summary>
        internal static string Wizard_Label_UpdateView {
            get {
                return ResourceManager.GetString("Wizard_Label_UpdateView", resourceCulture);
            }
        }
    }
}
