//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rationally.Visio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShapeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShapeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rationally.Visio.ShapeNames", typeof(ShapeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        internal static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeDescription.
        /// </summary>
        internal static string AlternativeDescription {
            get {
                return ResourceManager.GetString("AlternativeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeIdent.
        /// </summary>
        internal static string AlternativeIdentifier {
            get {
                return ResourceManager.GetString("AlternativeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives.
        /// </summary>
        internal static string Alternatives {
            get {
                return ResourceManager.GetString("Alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeState.
        /// </summary>
        internal static string AlternativeState {
            get {
                return ResourceManager.GetString("AlternativeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeTitle.
        /// </summary>
        internal static string AlternativeTitle {
            get {
                return ResourceManager.GetString("AlternativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternative.
        /// </summary>
        internal static string TypeAlternative {
            get {
                return ResourceManager.GetString("TypeAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternativeDescription.
        /// </summary>
        internal static string TypeAlternativeDescription {
            get {
                return ResourceManager.GetString("TypeAlternativeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternativeIdentifier.
        /// </summary>
        internal static string TypeAlternativeIdentifier {
            get {
                return ResourceManager.GetString("TypeAlternativeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternatives.
        /// </summary>
        internal static string TypeAlternatives {
            get {
                return ResourceManager.GetString("TypeAlternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternativeState.
        /// </summary>
        internal static string TypeAlternativeState {
            get {
                return ResourceManager.GetString("TypeAlternativeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternativeTitle.
        /// </summary>
        internal static string TypeAlternativeTitle {
            get {
                return ResourceManager.GetString("TypeAlternativeTitle", resourceCulture);
            }
        }
    }
}
