//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rationally.Visio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VisioFormulas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisioFormulas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rationally.Visio.VisioFormulas", typeof(VisioFormulas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.{0}.Action.
        /// </summary>
        internal static string Action_Action {
            get {
                return ResourceManager.GetString("Action_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.{0}.Disabled.
        /// </summary>
        internal static string Action_Disabled {
            get {
                return ResourceManager.GetString("Action_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.{0}.FlyoutChild.
        /// </summary>
        internal static string Action_IsFlyoutChild {
            get {
                return ResourceManager.GetString("Action_IsFlyoutChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.{0}.Menu.
        /// </summary>
        internal static string Action_MenuName {
            get {
                return ResourceManager.GetString("Action_MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative State.
        /// </summary>
        internal static string AlternativeState_ShapeMaster {
            get {
                return ResourceManager.GetString("AlternativeState_ShapeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_ALTERNATIVE_MENU.
        /// </summary>
        internal static string EventId_AddAlternative {
            get {
                return ResourceManager.GetString("EventId_AddAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_ALTERNATIVE_MENU.
        /// </summary>
        internal static string EventId_DeleteAlternative {
            get {
                return ResourceManager.GetString("EventId_DeleteAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string Formula_EscapedValue {
            get {
                return ResourceManager.GetString("Formula_EscapedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.Index.Value.
        /// </summary>
        internal static string Formula_Index {
            get {
                return ResourceManager.GetString("Formula_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUEUEMARKEREVENT(&quot;{0}&quot;).
        /// </summary>
        internal static string Formula_QUEUMARKEREVENT {
            get {
                return ResourceManager.GetString("Formula_QUEUMARKEREVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.rationallyType.Value.
        /// </summary>
        internal static string Formula_RationallyType {
            get {
                return ResourceManager.GetString("Formula_RationallyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \RationallyHidden.vssx.
        /// </summary>
        internal static string HiddenStencil {
            get {
                return ResourceManager.GetString("HiddenStencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB({0},{1},{2}).
        /// </summary>
        internal static string RGB_Color_Formula {
            get {
                return ResourceManager.GetString("RGB_Color_Formula", resourceCulture);
            }
        }
    }
}
